#!/usr/bin/env ruby

require "thor"
require_relative "../lib/flo"

class FloCLI < Thor
  class_option :host, default: "localhost", aliases: :H
  class_option :port, default: 3000, type: :numeric, aliases: :p

  desc "produce", "Used to produce events onto the stream"
  option :parent, aliases: :P, banner: "COUNTER.ACTOR"
  option :event_data, aliases: :d
  option :namespace, aliases: :n, required: true
  def produce()
    Flo.config do |c|
      c.host = options[:host]
      c.port = options[:port]
    end

    client = Flo::Client.new
    client.connect
    ack = client.produce(options[:namespace], options[:event_data], parent: Flo::EventId.parse(options[:parent]))
    puts ack
    client.disconnect
  end

  desc "consume", "Used to read events from the stream"
  option :limit, type: :numeric, aliases: :l
  option :start_after, type: :numeric, aliases: :s, banner: "COUNTER.ACTOR"
  option :tail, type: :boolean, aliases: :t
  option :namespace, aliases: :n, default: "/**/*"
  def consume()
    puts "consuming"
  end

end

FloCLI.start(ARGV)
